#!/bin/bash

SLAVEEXE=$1
BASEPORT=$2
DEVICE=$3

if [ "$SLAVEEXE" == "" ]
then
  >&2 echo "usage: $0 <slave-exe> [ <listing-port> ]"
  exit 1
fi

if [ "$BASEPORT" == "" ]
then
  >&2 echo "WARNING: no port configured, using 10000"
  BASEPORT=10000
fi

if [ "$DEVICE" == "" ]
then
  DEVICE=`ip addr show up | perl -n -e 'print "$1\n" if /^[0-9]+: ([^:]+):/ && !("$1" eq "lo")' | head -n 1`
  >&2 echo "WARNING: no device configured, using $DEVICE"
  BASEPORT=10000
fi

LOCALIP=`ip addr show dev $DEVICE | perl -n -e 'print $1 if /inet ([0-9\.]+)\/[0-9]+ brd/'`
CPUUNITS=`grep '^model name' /proc/cpuinfo | wc -l`
for i in `seq 1 $CPUUNITS`
do
   echo "Starting up slave node... "
   $SLAVEEXE Slave $LOCALIP $(($BASEPORT + $i)) 2>&1 &
done

